config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  get 'websites/random' => 'websites#random'
  
  resources :categories
  resources :websites

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :children, class_name: 'Category', foreign_key: 'parent_id'
	belongs_to :parent, class_name: 'Category', foreign_key: 'parent_id'

	has_and_belongs_to_many :keywords

  def get_children
  	return Category.where(:parent_id => id)
  end

  def get_parents
  	parents = []
  		
  	if parent_id != nil 
  		parents.push(parent.name)
  		parents.push(*parent.get_parents)
  	end

  	return parents
  end

  def get_categories 
  	return get_parents.push(name)
  end


end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
	has_and_belongs_to_many :categories
	has_and_belongs_to_many :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base

	has_and_belongs_to_many :keywords
end

app/models/rules.rb
class Rules


  def Rules.sex_with_an_object(website) 
        
    person = website.get_keywords_in_category('people').sample
    item = website.get_keywords_in_category('objects').sample
    picture = website.get_picture_for_keyword([person, item]);

    website.title = "Did " + person.name + " have sex with a " + item.name + "?"
    website.description = "Has the " + person.synonym + " had sexual relations with " + item.synonym + "?" + " What this damning report exposes could shock you!"
    website.picture_id = picture.id
    website.keyword_id = item.id
    website.text = "No. No they didn't. The report was actually unrelated to " + item.name

    # return "sex " + website.title
  end


  def Rules.religion(website) 

    person = website.get_keywords_in_category('people').sample
    religion = website.get_keywords_in_category('religions').sample
    religion2 = website.get_keywords_in_category('religions').select{|r| r.id != religion.id}.sample
    picture = website.get_picture_for_keyword([person, religion]);

    website.title = "Has " + person.name + " got plans to ban " + religion.name + "?"
    website.description = "Does the " + person.synonym + " want to eradicate the " + religion.synonym + " in favour of " + religion2.name + "?"
    website.picture_id = picture.id
    website.keyword_id = religion.id
    website.text = "No. It's utter nonsense."
  end  

  def Rules.fart_smeller(website) 

    person = website.get_keywords_in_category('people').sample
    picture = website.get_picture_for_keyword([person]);

    website.title = "Is " + person.name + " a smart feller, or a fart smeller?"
    website.description = "What we found out will SHOCK you!"
    website.picture_id = picture.id
    website.keyword_id = person.id
    website.text = "We have evidence of neither."
  end

  def Rules.new_rule2(website) 
    sex_with_an_object(website)
  end


end

app/models/website.rb
class Website < ActiveRecord::Base

  has_one :keyword

# generates a random website
  def get_random_website
  	 methods = Rules.methods(false)
  	 random_method = methods.sample
  	 Rails.logger.info(random_method)
  	 Rules.send(random_method, self)
  end

 #  def get_stuff 
 #  	person = get_keywords_in_category('people').sample
 #  	item = get_keywords_in_category('objects').sample
	# picture = get_picture_for_keyword(person, item);

	# self.title = "Did " + person.name + " have sex with a " + item.name + "?"
	# self.description = "Has the " + person.synonym + " had sexual relations with " + item.synonym + "?" + " What this damning report exposes could shock you!"
	# self.picture_id = picture.id
	# self.keyword_id = item.id
	# self.text = "No. No he didn't. The report was actually unrelated to " + item.name
 #  end

  def get_keywords_in_category(category_name)
  	return Category.where(:name => category_name).map{|category| category.keywords}.flatten
  end

  def get_websites_for_keyword(keyword)
  	return Website.where(:keyword_id => keyword.id)
  end

  def get_picture_for_keyword(keywords) 
  	pictures = keywords.map{|keyword| keyword.pictures}.flatten
  	return !pictures.blank? ? pictures.sample : Picture.find(3)
  end

  def picture 
  	return Picture.find(picture_id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def index
  	@categories = Category.where(:parent => nil)
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)

  	if @category.save
  		redirect_to @category
  	else
  		render 'new'
  	end
  end



private
  def category_params
    params.require(:category).permit(:name, :parent)
  end




end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  def index
  	@websites = Website.all
  end

  def show
    @website = Website.find(params[:id])
  end

  def new
  	@website = Website.new
  	@website.get_random_website
  end

  def create
  	@website = Website.new(website_params)

  	if @website.save
  		redirect_to @website
  	else
  		render 'new'
  	end
  end

  def random
  	new
  	render 'show'
  end


private
  def website_params
    params.require(:website).permit(:title, :description, :picture_id, :text, :keyword_id)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	redirect_to url_for(:controller => :websites, :action => :random)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_category.html.erb
<li>
	<b><%= category.name %></b> categories: <%= category.get_categories %> 
	items: 
	<% category.keywords.each do |keyword| %>
      <%= keyword.name %>, 
  	<% end %>
	<%#= link_to 'Show', category_path(category) %>
	<ul><%= render partial: "category", collection: category.get_children %></ul>
</li>

app/views/categories/index.html.erb
  
<% content_for :title, "All categories" %>
<h3>All categories</h3>

<ul>
  	<%= render partial: 'category', collection: @categories %>
</ul>


<%#= Keyword.where(:name 'fish') %>
<%# Category.find_by_name('people').keywords.each do |keyword| %>
<% Category.where(:name => 'people').map{|category| category.keywords}.flatten.each do |keyword| %>
      <%= keyword.name %>
      <% keyword.pictures.each do |picture| %>
      	<%= image_tag picture.url %>
      <% end %>
<% end %>

app/views/categories/new.html.erb
  
<% content_for :title, "Add new category" %>

<h3>Add new category</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-3425420436339485",
    enable_page_level_ads: true
  });
</script>

  <title>News Nugget - <%= yield(:title) %></title>

<%= favicon_link_tag 'favicon.ico' %>

<meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : 'News Nugget' %>" />
<meta property="og:url" content="https://news-nugget.herokuapp.com<%= yield(:url) %>" />
<meta property="og:type" content="website" />
<meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : 'Prime nuggets of news.' %>" />
<meta property="og:image" content="https://news-nugget.herokuapp.com<%= content_for?(:image) ? yield(:image) : '/default.jpg' %>" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div id='footer'>This website is for entertainment purposes only.</div>


</body>
</html>

app/views/websites/_header.html.erb
<div id="header-container">


	<div id='header-non-fixed'>
		<div class='icon'><%= image_tag 'nuggets.jpg', alt: "News Nugget", height: "60", width: "100" %></div>
		<div class='heading'>News Nugget</div>
	</div>


	<div id='header-fixed'>News Nugget</div>


</div>

app/views/websites/_preview.html.erb
<div class='preview-container'>
	<%= link_to website_path(website) do %>
		<% picture = website.picture %>
		<div class='preview-image'><%= image_tag picture.url, alt: picture.description%></div>
		<div class='preview-text'>
			<div class='preview-title'><%= website.title %></div> 
			<div class='preview-description'><%= website.description %></div>
		</div>
	<% end %>
</div>

app/views/websites/index.html.erb
<% @websites.each do |website| %>

	<div><%= website.title %> <%= link_to 'Show', website_path(website) %></div>
<% end %>

app/views/websites/new.html.erb
<h1>New Article</h1>

<% content_for :title, @website.title %>

<%= form_for @website do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => 200 %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "150x3" %>
  </p>
 
  <p>
    <%= f.label :picture_id %><br>
    <%= f.text_area :picture_id %>
  </p>

  <p>
    <%= f.label :keyword_id %><br>
    <%= f.text_area :keyword_id %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, size: "100x2" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/websites/show.html.erb
<% Rails.logger.info @website.attributes %>
<% picture = @website.picture %>

<% content_for :title, @website.title %>
<% content_for :description, @website.description %>
<% content_for :image, image_path(picture.url) %>
<% content_for :url, @website.id.present? ? @website.id.to_s : nil %>

<%= render partial: 'header' %>

<div class='article-background'>
	<div class='article'>

		<div class='article-title'><%= @website.title %></div>
		<div class='article-image'><%= image_tag picture.url, alt: picture.description, width: "300" %></div>
		<div class='article-description-container'><span class='article-description'><%= @website.description %></span></div>


		<div class='article-text'><%= @website.text %></div>
	</div>
</div>


<div class='tags'>
<h3>Other News Nuggets</h3>
	<% keyword = Keyword.find(@website.keyword_id) %>
	<% categories = keyword.categories.map{|category| category.get_categories} %>
	<% keywords = categories.map{|category| @website.get_keywords_in_category(category)}.flatten %>
	<%#= keywords %>
	<% other_websites = keywords.map{|keyword| @website.get_websites_for_keyword(keyword)}.flatten.select{|website| website.id != @website.id} %>

	<% all_websites = Website.all %>
	<% while other_websites.size < 1 do %>
		<% other_websites.push(all_websites.sample) %>
	<% end %>

	<% other_websites.sample(3).each do |website| %>
		<%= render partial: 'preview', locals: {website: website} %>
	<% end %>
	<br>
	<br>
</div>

app/views/welcome/index.html.erb
<%= link_to 'Random News', websites_random_path %>